# Generated by Django 4.2.7 on 2023-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
