# Generated by Django 4.2.7 on 2023-11-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0003_alter_album_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
